### PR TITLE
closes #132 Solves HMR issue by assigning props to the Form class

### LINKED ISSUE #132: React Native Hot Reload breaks tcomb-form-native
### Version

- `tcomb-form-native`: `0.4.0`
- `react-native`:  `0.22.0-rc4`

### Expected behaviour

React Native 0.22 introduces Hot Reload and after a code change the hot reload behaviour should not break the plugin.

### Actual behaviour

After a code change the plugin throws an error.

### Steps to reproduce

1. New react native project
2. Add a `tcomb-form-native` form
3. Enabled Hot Reload in the app
4. Make a change while the app is running

### Stack trace and console log

The error that is thrown:
`[tcomb][tcomb-form-native] missing stylesheet config`

### Additional information

- The error is thrown in the `Form.render` method by the assert
- The `stylesheet` variable is indeed `undefined` after a code change
- The other asserts fail as well (`templates` and `i18n`)
- Hot Reload works by wrapping components with a shell that can reloads its component, so somehow the assignments in the `index.js` file are ignored

### PR DESCRIPTION
**Pull request by alvaromb**
...as suggested in the issue. 

Tests doesn't pass because of https://github.com/gcanti/tcomb-form-native/issues/134. Can be tested by changing from `require('./datepicker')` to `require('./datepicker.ios.js')`.

### CODE REVIEW

**Comment by alvaromb** [comment]
Further test is needed, though.

**Comment by gcanti** [comment]
@alvaromb moving 

```js
var i18n = require('./i18n/en');
var templates = require('./templates/bootstrap');
var stylesheet = require('./stylesheets/bootstrap');
```

inside `lib/components.js` seems wrong to me. You end up loading those modules even if you use other templates, locales or stylesheets.

my suggestion (as per https://github.com/gcanti/tcomb-form-native/issues/132#issuecomment-201236313) would be:

```js
// lib/components.js

...

class Form extends React.Component {

  ...

  render() {

    const type = this.props.type;
    const options = this.props.options || nooptions;
    const stylesheet = this.props.stylesheet; // <= read from props, was Form.stylesheet
    const templates = this.props.templates; // <= read from props, was Form.templates
    const i18n = this.props.i18n; // <= read from props, was Form.i18n

    t.assert(t.isType(type), `[${SOURCE}] missing required prop type`);
    t.assert(t.Object.is(options), `[${SOURCE}] prop options must be an object`);
    t.assert(t.Object.is(stylesheet), `[${SOURCE}] missing stylesheet config`);
    t.assert(t.Object.is(templates), `[${SOURCE}] missing templates config`);
    t.assert(t.Object.is(i18n), `[${SOURCE}] missing i18n config`);

    ...

  }

}
```

```js
// index.js

import t from './lib';
import i18n from './lib/i18n/en';
import templates from './lib/templates/bootstrap';
import stylesheet from './lib/stylesheets/bootstrap';

t.form.Form.templates = templates;
t.form.Form.stylesheet = stylesheet;
t.form.Form.i18n = i18n;

t.form.Form.defaultProps = {
  templates: t.form.Form.templates
  stylesheet: t.form.Form.stylesheet
  i18n: t.form.Form.i18n
};

export default t;
```

That would be a backward compatible change. Then **if** you want to enable HMR **you must** import `tcomb-form-native/lib` and pass in `i18n`, `templates` and `stylesheet` as props. Otherwise just import `tcomb-form-native` as usual.

(I'm reasoning based on this quote from the first #132 comment)

> Hot Reload works by wrapping components with a shell that can reloads its component, so somehow the assignments in the index.js file are ignored

I'm missing something?

**Comment by alvaromb** [comment]
I'll give it a spin and test it tomorrow. Don't know if having to manually inject those props in order to make HMR work is right, but honestly I come from the objc world and I don't really know the implications of `require`/`import` in terms of module loading performance.

**Comment by alvaromb** [comment]
On the other side, it's very hard to keep with FB's update cycle when you're a lone developer maintaining more than five apps :wrench: :nut_and_bolt:.

**Comment by gcanti** [comment]
I feel you pain. I just don't want to screw up the imports of `tcomb-form-native` just for the sake of HMR.
I'm willing to solve this issue but, since you and I don't use HMR, I'd like more help from people who do, if they are really interested.

**Comment by cpunion** [comment]
Updated to react-native@0.24, HMR works fine with tcomb-form-native on iPhone 5s device, but has same problem on iPhone 5s simulator.

**Comment by cpunion** [comment]
Sorry, the reason is my device was logged in, it didn't display form.

**Comment by thomasjonas** [comment]
Working with the adjustments made in this PR I no longer get the red box with errors. It's a workable situation again, so I would like to see this merged :) Thanks so much for all your work, you guys!

On a side note: I'm not sure how HMR is supposed to work exactly, but when I change a custom form stylesheet it's not being changed immediately. It is changed when I reload the view back navigating my app. When I change other stylesheets (for components other than tcomb-form-native) I does immediately reflect the changes. Not sure if it's my implementation or the way tcomb-form-native implements HMR. It's not a big deal either way.

**Comment by justim** [comment]
For me it also works like a charm, so at least it's a good approach for the HMR issue.

The stylesheets do update for me when I use it like this:

```json
"tcomb-form-native": "git://github.com/APSL/tcomb-form-native#639c5d5"
```

```js
const options = {
    fields: {
        message: {
            stylesheet: {
                textbox: {
                    normal: {
                        height: 100,
    // ...
};

render() {
    return <Form
        options={options}
    />;
}
```

Changing the height immediately changes the app.

And after a bit of further investigation, the approach that @gcanti suggested above (setting the `defaultProps` in the `index.js` file) seems to work fine as well :)

**Comment by gcanti** [comment]
@justim thanks for your tests. A question, when you say:

> And after a bit of further investigation, the approach that @gcanti suggested above (setting the defaultProps in the index.js file) seems to work fine as well :)

which module are you importing? 

```js
import t from 'tcomb-form-native'
```

or

```js
import t from 'tcomb-form-native/lib' // and then pass in i18n, templates and stylesheet as props
```

**Comment by justim** [comment]
I use this one:

```js
import tcomb from 'tcomb-form-native';
```

**Comment by gcanti** [comment]
Great, @alvaromb would you like to update this PR?

In order to be backward compatible with [Customizations](https://github.com/gcanti/tcomb-form-native#customizations), I think we should also read from `Form`:

```js
// lib/components.js

...

class Form extends React.Component {

  ...

  render() {

    const type = this.props.type;
    const options = this.props.options || nooptions;
    const stylesheet = this.props.stylesheet || Form.stylesheet; // <= read from props or Form
    const templates = this.props.templates || Form.templates; // <= read from props or Form
    const i18n = this.props.i18n || Form.i18n; // <= read from props or Form

    t.assert(t.isType(type), `[${SOURCE}] missing required prop type`);
    t.assert(t.Object.is(options), `[${SOURCE}] prop options must be an object`);
    t.assert(t.Object.is(stylesheet), `[${SOURCE}] missing stylesheet config`);
    t.assert(t.Object.is(templates), `[${SOURCE}] missing templates config`);
    t.assert(t.Object.is(i18n), `[${SOURCE}] missing i18n config`);

    ...

  }

}
```

```js
// index.js

import t from './lib';
import i18n from './lib/i18n/en';
import templates from './lib/templates/bootstrap';
import stylesheet from './lib/stylesheets/bootstrap';

t.form.Form.templates = templates;
t.form.Form.stylesheet = stylesheet;
t.form.Form.i18n = i18n;

t.form.Form.defaultProps = {
  templates: t.form.Form.templates
  stylesheet: t.form.Form.stylesheet
  i18n: t.form.Form.i18n
};

export default t;
```

**Comment by alvaromb** [comment]
Ok! I'll do this evening 👍

**Comment by alvaromb** [comment]
Just updated the PR @gcanti.

Should we add something to the docs?

File: lib/components.js [hunk 1]
```diff
@@ -523,19 +523,19 @@ class Form extends React.Component {
...
-    var type = this.props.type;
-    var options = this.props.options || nooptions;
-    var stylesheet = Form.stylesheet;
-    var templates = Form.templates;
-    var i18n = Form.i18n;
+    const type = this.props.type;
+    const options = this.props.options || nooptions;
+    const stylesheet = this.props.stylesheet;
+    const templates = this.props.templates;
+    const i18n = this.props.i18n;
```
Comment (gcanti) [inline lib/components.js]: In order to be backward compatible we should also read from `Form`:

```js
const stylesheet = this.props.stylesheet || Form.stylesheet;
const templates = this.props.templates || Form.templates;
const i18n = this.props.i18n || Form.i18n;
```

File: lib/components.js [hunk 2]
```diff
@@ -523,19 +523,19 @@ class Form extends React.Component {
...
 
     t.assert(t.isType(type), `[${SOURCE}] missing required prop type`);
     t.assert(t.Object.is(options), `[${SOURCE}] prop options must be an object`);
-    t.assert(t.Object.is(stylesheet), `[${SOURCE}] missing stylesheet config`);
-    t.assert(t.Object.is(templates), `[${SOURCE}] missing templates config`);
-    t.assert(t.Object.is(i18n), `[${SOURCE}] missing i18n config`);
+    t.assert(t.Object.is(this.props.stylesheet), `[${SOURCE}] missing stylesheet config`);
+    t.assert(t.Object.is(this.props.templates), `[${SOURCE}] missing templates config`);
+    t.assert(t.Object.is(this.props.i18n), `[${SOURCE}] missing i18n config`);
```
Comment (gcanti) [inline lib/components.js]: and then use those variables:

```js
t.assert(t.Object.is(stylesheet), `[${SOURCE}] missing stylesheet config`);
t.assert(t.Object.is(templates), `[${SOURCE}] missing templates config`);
t.assert(t.Object.is(i18n), `[${SOURCE}] missing i18n config`);
```

File: lib/components.js (hunk 1 above)
Comment (alvaromb) [inline lib/components.js]: Sorry, accidentally deleted this while deleting the comment.

**Comment by alvaromb** [comment]
Done @gcanti

**Comment by qpowell** [comment]
Thanks for all the hard work!

**Comment by alvaromb** [comment]
Sorry for the delay, I'm not using HRM right now so this has delayed a bit the work.

**Comment by gcanti** [comment]
Thanks @alvaromb going to merge and release :-)
